[package]
name = "gitdot_client"
version = "0.1.0"
edition = "2024"

[dependencies]
gitdot_api = { path = "../api" }
reqwest = { version = "0.13.1", features = ["json"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
