[package]
name = "gitdot_client"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
gitdot_api = { path = "../api" }
reqwest = { workspace = true }
uuid = { workspace = true }
