#:schema https://www.gitdot.io/schema/gitdot-ci.json

[[builds]]
trigger = "push_to_main"
tasks = ["stream"]

[[tasks]]
name = "stream"
command = 'i=1; while [ $i -le 180 ]; do echo "[STREAM] second $i $(date +%H:%M:%S)"; for j in 1 2 3 4 5 6 7 8 9 10; do echo "  line $j"; done; sleep 1; i=$((i+1)); done'
