#:schema https://www.gitdot.io/schema/gitdot-ci.json

[[builds]]
trigger = "pull_request"
tasks = ["build", "lint", "test"]

[[tasks]]
name = "build"
command = "echo 'Your build command here'"

[[tasks]]
name = "lint"
command = "echo 'Your lint command here'"

[[tasks]]
name = "test"
command = "echo 'Your test command here'"
waits_for = ["build", "lint"]
