#:schema https://www.gitdot.io/schema/gitdot-ci.json

[[builds]]
trigger = "push_to_main"
tasks = ["build", "lint", "check"]

[[tasks]]
name = "build"
command = "cargo clean && just build"

[[tasks]]
name = "lint"
command = "scripts/log-every-second.sh"

[[tasks]]
name = "check"
command = "scripts/log-every-second.sh"
