[package]
name = "gitdot-api"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true }
gitdot-api-derive = { path = "./derive" }
http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
