[package]
name = "gitdot_core"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
nutype = { workspace = true }
serde = { workspace = true }
sqlx = { version = "0.8.6", features = ["runtime-tokio", "postgres", "uuid", "chrono"] }
thiserror = { workspace = true }
uuid = { workspace = true }
