[package]
name = "gitdot_api"
version = "0.1.0"
edition = "2024"

[dependencies]
gitdot_api_derive = { path = "./derive" }
chrono = { workspace = true }
http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
