[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
api_derive = { path = "../api_derive" }
chrono = { workspace = true }
http = "1.4.0"
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
